### ISSUE TITLE
Does not buid on Armbian

### ISSUE THREAD

**Issue by Siggemada** [MobotixAG/live666#1]
Linux bananapi 4.13.16-sunxi #20 SMP Fri Nov 24 19:50:07 CET 2017 armv7l GNU/Linux

./genMakefiles linux
make -j4make -j4

In file included from include/NetAddress.hh:25:0,
                 from include/NetInterface.hh:25,
                 from include/Groupsock.hh:29,
                 from Groupsock.cpp:20:
../UsageEnvironment/include/HashTable.hh:27:20: fatal error: export.h: No such file or directory
 #include "export.h"
                    ^
compilation terminated.
Makefile:31: recipe for target 'Groupsock.o' failed
make[1]: *** [Groupsock.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from include/NetAddress.hh:25:0,
                 from include/GroupEId.hh:29,
                 from GroupEId.cpp:20:
../UsageEnvironment/include/HashTable.hh:27:20: fatal error: export.h: No such file or directory
 #include "export.h"
                    ^
compilation terminated.
Makefile:31: recipe for target 'GroupEId.o' failed
make[1]: *** [GroupEId.o] Error 1
In file included from include/NetAddress.hh:25:0,
                 from include/GroupsockHelper.hh:25,
                 from GroupsockHelper.cpp:21:
../UsageEnvironment/include/HashTable.hh:27:20: fatal error: export.h: No such file or directory
 #include "export.h"
                    ^
compilation terminated.
In file included from include/NetAddress.hh:25:0,
                 from include/NetInterface.hh:25,
                 from NetInterface.cpp:21:
../UsageEnvironment/include/HashTable.hh:27:20: fatal error: export.h: No such file or directory
 #include "export.h"
                    ^
compilation terminated.
Makefile:31: recipe for target 'GroupsockHelper.o' failed
make[1]: *** [GroupsockHelper.o] Error 1
Makefile:31: recipe for target 'NetInterface.o' failed
make[1]: *** [NetInterface.o] Error 1
make[1]: Leaving directory '/home/xxxxxx/live666/groupsock'
Makefile:33: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by moboie** [comment]
Did you try to use CMake instead of the live555 makefiles?
Those makefiles are not supported so far.

**Comment by moboie** [comment]
Please try again with release 1.14.3.
This issue should be fixed now.

**Comment by Siggemada** [comment]
Yes, works! Great job!
