### ISSUE TITLE
New version does not build with the original makefiles on linux.

### ISSUE THREAD

**Issue by Siggemada** [MobotixAG/live666#2]
xxx@bananapi:~/live/live666$ make -j4
cd liveMedia ; make
make[1]: Entering directory '/home/xxx/live/live666/liveMedia'
c++ -c -Iinclude -I../UsageEnvironment/include -I../groupsock/include -I. -O2 -DSOCKLEN_T=socklen_t -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -Wall -DBSD=1   MediaSession.cpp
c++ -c -Iinclude -I../UsageEnvironment/include -I../groupsock/include -I. -O2 -DSOCKLEN_T=socklen_t -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -Wall -DBSD=1   PassiveServerMediaSubsession.cpp
c++ -c -Iinclude -I../UsageEnvironment/include -I../groupsock/include -I. -O2 -DSOCKLEN_T=socklen_t -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -Wall -DBSD=1   OnDemandServerMediaSubsession.cpp
c++ -c -Iinclude -I../UsageEnvironment/include -I../groupsock/include -I. -O2 -DSOCKLEN_T=socklen_t -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -Wall -DBSD=1   FileServerMediaSubsession.cpp
c++ -c -Iinclude -I../UsageEnvironment/include -I../groupsock/include -I. -O2 -DSOCKLEN_T=socklen_t -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -Wall -DBSD=1   MPEG4VideoFileServerMediaSubsession.cpp
c++ -c -Iinclude -I../UsageEnvironment/include -I../groupsock/include -I. -O2 -DSOCKLEN_T=socklen_t -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -Wall -DBSD=1   H264VideoFileServerMediaSubsession.cpp
MediaSession.cpp: In constructor ‘MediaSession::MediaSession(UsageEnvironment&)’:
MediaSession.cpp:63:23: error: ‘FALSE’ was not declared in this scope
     fHasPlayStartTime(FALSE), fHasPlayEndTime(FALSE),
                       ^~~~~
MediaSession.cpp: In member function ‘Boolean MediaSession::parseSDPAttribute_range(const char*)’:
MediaSession.cpp:397:27: error: ‘TRUE’ was not declared in this scope
       fHasPlayStartTime = TRUE;
                           ^~~~
MediaSession.cpp:401:25: error: ‘TRUE’ was not declared in this scope
       fHasPlayEndTime = TRUE;
                         ^~~~
MediaSession.cpp: In member function ‘Boolean MediaSubsession::parseSDPAttribute_fmtp(const char*)’:
MediaSession.cpp:1111:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
     if (strncmp(sdpLine, "a=fmtp:", 7) != 0) break; sdpLine += 7;
     ^~
MediaSession.cpp:1111:53: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
     if (strncmp(sdpLine, "a=fmtp:", 7) != 0) break; sdpLine += 7;
                                                     ^~~~~~~
Makefile:32: recipe for target 'MediaSession.o' failed
make[1]: *** [MediaSession.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/xxx/live/live666/liveMedia'
Makefile:33: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Siggemada** [comment]
Same result with cmake.

**Comment by moboie** [comment]
Thank you for the hint.
The problem should be fixed with 1.15.2, please try.

**Comment by Siggemada** [comment]
Works great! Thanks!
