### ISSUE TITLE
Missing locale definitions on macOS

### ISSUE THREAD

**Issue by gizak** [MobotixAG/live666#3]
When build on macOS some locale related errors will occurr, such as:

```
live666-releases-1.18.0/liveMedia/include/Locale.hh:68:3: error: unknown type
      name 'locale_t'
  locale_t fLocale, fPrevLocale;
```

It shows we are missing locale definitions. Add `-DNEED_XLOCALE_H=1` will fix this (hinted from using genMakefiles generated Makefile).

**Comment by mobokai** [comment]
Thanks.
Fixed with Release 1.19.0.
